### ISSUE TITLE
Newbie question: broken highlighting?

### ISSUE THREAD

**Issue by gvolpe** [tree-sitter/tree-sitter-scala#134]
Highlights are broken (at least for me) since https://github.com/tree-sitter/tree-sitter-scala/pull/125, as the PR explains. Looks like `nvim-tresitter` synced up [2 hours ago](https://github.com/nvim-treesitter/nvim-treesitter/commit/9a257d989a526c413a28c252c4ec9113a7d35a28).

Is that all that's necessary to fix highlighting? Or something extra work is necessary to fix it? 

I updated both `nvim-treesitter` and `tree-sitter-scala` to the latest commits, but highlighting is still broken for me. Though, it could also be that I'm doing something wrong if this is supposed to work normally 😄 

Appreciate your comments!

**Comment by keynmol** [comment]
Hi @gvolpe - unfortunately the queries for all parsers are synced manually, we plan to do it today.

In the meantime you can test the current version of highlights using the instructions in https://github.com/tree-sitter/tree-sitter-scala/pull/103

In the future we will try to make sure we update grammar and highlights in a backwards-compatible way, given there's always a discrepancy due to manual process.

**Comment by keynmol** [comment]
See https://github.com/nvim-treesitter/nvim-treesitter/pull/4153 as Chris is apparently already on it

**Comment by gvolpe** [comment]
Awesome! Thanks for the pointer. I'll try to use that PR to get it working in the meantime :)

**Comment by ckipp01** [comment]
@gvolpe you'll want to make sure you have the latest parser from https://github.com/tree-sitter/tree-sitter-scala/pull/135  as well.

**Comment by gvolpe** [comment]
@ckipp01 that did the trick, thank you! Crazy how many things are involved 😄
