### ISSUE TITLE
highlight groups

### ISSUE THREAD

**Issue by stumash** [tree-sitter/tree-sitter-scala#28]
The [list of languages with tree-sitter highlighting](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages) doesn't include scala, because tree-sitter-scala is 'missing' a `queries/highlights.scm` file [like java has](https://github.com/tree-sitter/tree-sitter-java/blob/master/queries/highlights.scm).

There must be a vim user among **ye beneficent contributors**?

**Comment by ckipp01** [comment]
@stumash keep in mind that for `nvim-treesitter` to use the queries they need to be defined in https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries, not really in this repo. I know some tree sitter repos do have them defined in their language repo in order to power highlighting for other tools etc, but `nvim-treesitter` specifically pulls them from their own queries.

**Comment by stumash** [comment]
Hmm I didn't know that, thanks. Going by the fact that the `highlights.scm` file for java in the tree-sitter main repo is much bigger than the one in the tree-sitter-java repo, I think my changes should go in that repo, not this one.

I've got some reading to do.
