### ISSUE TITLE
Need help getting access to NPM (please help us if you see this max :) )

### ISSUE THREAD

**Issue by hjdivad** [tree-sitter/tree-sitter-scala#344]
The latest release [appears to be 0.20.2](https://github.com/tree-sitter/tree-sitter-scala/releases/tag/v0.20.2) however the latest published package on npm is [0.19.0](https://www.npmjs.com/package/tree-sitter-scala).

Is NPM an official release channel for this package?  If so could we have the latest version published there.  Thanks.

**Comment by eed3si9n** [comment]
I've been making releases by creating tags and making Rust releases, but I didn't know that npm was one of the bindings tree-sitter-scala has made releases.

**Comment by hjdivad** [comment]
@eed3si9n that makes sense.  Do you expect to restart publishing new releases to npm?

Put another way, for someone using tree-sitter's node bindings, what's the best way to consume `tree-sitter-scala`?

**Comment by eed3si9n** [comment]
It looks like @maxbrunsfeld and @queerviolet maintain the npm package https://www.npmjs.com/package/tree-sitter-scala. I don't know the system works, but if they could add me, I'd be happy to try publishing for the current tags. Otherwise, I am not sure.

**Comment by sjrd** [comment]
First: thank you for this project :)

Reviving a little bit this topic: if and when this gets done, could you also include the `.wasm` build of tree-sitter-scala in the process? Some parsers include their `.wasm` in the built npm package, which is ideal for consumption. Another possibility is to distribute that file in the GitHub Release associated with the tag.

FYI, following the [tree-sitter documentation](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web#generate-wasm-language-files), generating the `.wasm` file is done as
```scala
npx tree-sitter build-wasm .
```
when in the directory of the `tree-sitter-scala`. If done in a `package.json` script, `"tree-sitter build-wasm ."` is enough.

---

I can successfully use the `tree-sitter-scala.wasm` built by the above command on any platform. But *building* it requires the setup already necessary for developing a tree-sitter language support. It would be helpful if it were built as part of the release process of tree-sitter-scala itself, since it already has all the required infrastructure.

**Comment by ckipp01** [comment]
Let's try pinging one more time. @maxbrunsfeld or @queerviolet is there any chance that you'd be able to help us out with access to the NPM repository to continue publishing there?

**Comment by amaanq** [comment]
I'll help out here soon enough, working on standardizing the release process across the ecosystem for rust/python/npm (the bash, c, and python parsers are updated with this new process)

**Comment by antemasqued** [comment]
Attempting another reping since it's been about 7 months: cc @maxbrunsfeld 🙏🏼. If a week or so goes by, I'll attempt to email, though I'd like to refrain from doing that if I can.

**Comment by eed3si9n** [comment]
Here's a PR that cherry picks release automation - https://github.com/tree-sitter/tree-sitter-scala/pull/408

**Comment by eed3si9n** [comment]
https://www.npmjs.com/package/tree-sitter-scala/v/0.22.1 is out
